### ISSUE TITLE
Looks like the API for servers changed.

### ISSUE THREAD

**Issue by toastal** [nstinus/nordvpn#33]
```bash
No configuration files found or files too old. Updating now...
Downloading nordvpn config files...
md5sum(nordvpn.zip) != 
```

There's no md5sum value.

```bash
 λ ~ curl -sI https://nordvpn.com/api/files/zipv2
HTTP/2 301 
date: Sun, 01 Oct 2017 23:54:24 GMT
content-length: 0
set-cookie: __cfduid=d3e70af132e37a437537d71886b950ffb1506902064; expires=Mon, 01-Oct-18 23:54:24 GMT; path=/; domain=.nordvpn.com; HttpOnly
location: https://downloads-legacy.nordvpn.com/configs/archives/servers/legacy/config.zip
access-control-allow-origin: *
x-api-version: 1.x
x-frame-options: SAMEORIGIN
server: cloudflare-nginx
cf-ray: 3a7358cf084c6a13-LHR
```

There's no etag header to `grep` for and we have 301 to this legacy url.

Possible new API urls:
https://nordvpn.com/api/server
https://nordvpn.com/api/server/stats

**Comment by to266** [comment]
Also the servers json file might have had the structure changed:
```python
Traceback (most recent call last):
  File "./servers.py", line 158, in <module>
    df = pandas.read_json(args.servers_filename)
  File "/home/to266/anaconda3/lib/python3.6/site-packages/pandas/io/json/json.py", line 354, in read_json
    date_unit).parse()
  File "/home/to266/anaconda3/lib/python3.6/site-packages/pandas/io/json/json.py", line 422, in parse
    self._parse_no_numpy()
  File "/home/to266/anaconda3/lib/python3.6/site-packages/pandas/io/json/json.py", line 639, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None)
ValueError: Unexpected character found when decoding object value
```

**Comment by nstinus** [comment]
Confirmed. I sent them an email asking what the alternative should be. In
their doc, they still point to this zip URL for openvpn config.
It might help if you guys weigh in on this as well: support@nordvpn.com.

**Comment by nstinus** [comment]
The solution they offered does not appear to work.
I pushed a quick fix to disable the update for the time being.

**Comment by qguv** [comment]
Could you update the PKGBUILD on AUR as well? Thanks!

**Comment by nstinus** [comment]
I believe it was the case when you posted your comment. Please confirm whether you still have an issue.

**Comment by qguv** [comment]
Nope, it looks great now. Thanks @nstinus!
