### ISSUE TITLE
Unable to run program

### ISSUE THREAD

**Issue by xero-lib** [nstinus/nordvpn#46]
I can't run the program and I have absolutely no idea why.

```
[helix@vega ~]$ sudo nordvpn best
No configuration files found or files too old. Updating now...
Downloading nordvpn config files...
[nordvpn.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of nordvpn.zip or
        nordvpn.zip.zip, and cannot find nordvpn.zip.ZIP, period.
/usr/bin/nordvpn: line 113: msg_exit: command not found
Patching and installing files...
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
Traceback (most recent call last):
  File "/etc/openvpn/client/nordvpn/servers.py", line 158, in <module>
    df = pandas.read_json(args.servers_filename)
  File "/usr/lib/python3.9/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/usr/lib/python3.9/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/usr/lib/python3.9/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/usr/lib/python3.9/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/usr/lib/python3.9/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
```

I can't run the program and I have no idea why.

**Comment by xero-lib** [comment]
I have changed the login in `/etc/openvpn/client/nordvpn/credentials.conf` and changed owner to `openvpn`
